#ifndef LCC_TOKEN_PARSER
#define LCC_TOKEN_PARSER

#include <assert.h>
#include "lcc_token.c"
#include "lcc_status.h" 
#include "lcc_input_gather.c"

const int(*handlers[]) (struct lcc_input_wrapper *w, struct lcc_token *tk) = {
    &lcc_tk_eof__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_newline__parse, // '\n'
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_undefined__parse, // ' '
    &lcc_tk_space__parse, // ' '
    &lcc_tk_undefined__parse, // '!'
    &lcc_tk_str__parse, // '"'
    &lcc_tk_undefined__parse, // '#'
    &lcc_tk_undefined__parse, // '$'
    &lcc_tk_undefined__parse, // '%'
    &lcc_tk_undefined__parse, // '&'
    &lcc_tk_undefined__parse, // 'procurar melhor'
    &lcc_tk_undefined__parse, // '('
    &lcc_tk_undefined__parse, // ')'
    &lcc_tk_op__parse, // '*'
    &lcc_tk_op__parse, // '+'
    &lcc_tk_undefined__parse, // ',' confirmar
    &lcc_tk_op__parse, // '-'
    &lcc_tk_undefined__parse, // '.'
    &lcc_tk_op__parse, // '/'
    &lcc_tk_number__parse, // '0'
    &lcc_tk_number__parse, // '1'
    &lcc_tk_number__parse, // '2'
    &lcc_tk_number__parse, // '3'
    &lcc_tk_number__parse, // '4'
    &lcc_tk_number__parse, // '5'
    &lcc_tk_number__parse, // '6'
    &lcc_tk_number__parse, // '7'
    &lcc_tk_number__parse, // '8'
    &lcc_tk_number__parse, // '9'
    &lcc_tk_undefined__parse, // ':'
    &lcc_tk_semicolon__parse, // ';'
    &lcc_tk_undefined__parse, // '<'
    &lcc_tk_op__parse, // '='
    &lcc_tk_undefined__parse, // '>'
    &lcc_tk_undefined__parse, // '?'
    &lcc_tk_undefined__parse, // '@'
    &lcc_tk_sym__parse, // 'A'
    &lcc_tk_sym__parse, // 'B'
    &lcc_tk_sym__parse, // 'C'
    &lcc_tk_sym__parse, // 'D'
    &lcc_tk_sym__parse, // 'E'
    &lcc_tk_sym__parse, // 'F'
    &lcc_tk_sym__parse, // 'G'
    &lcc_tk_sym__parse, // 'H'
    &lcc_tk_sym__parse, // 'I'
    &lcc_tk_sym__parse, // 'J'
    &lcc_tk_sym__parse, // 'K'
    &lcc_tk_sym__parse, // 'L'
    &lcc_tk_sym__parse, // 'M'
    &lcc_tk_sym__parse, // 'N'
    &lcc_tk_sym__parse, // 'O'
    &lcc_tk_sym__parse, // 'P'
    &lcc_tk_sym__parse, // 'Q'
    &lcc_tk_sym__parse, // 'R'
    &lcc_tk_sym__parse, // 'S'
    &lcc_tk_sym__parse, // 'T'
    &lcc_tk_sym__parse, // 'U'
    &lcc_tk_sym__parse, // 'V'
    &lcc_tk_sym__parse, // 'W'
    &lcc_tk_sym__parse, // 'X'
    &lcc_tk_sym__parse, // 'Y'
    &lcc_tk_sym__parse, // 'Z'
    &lcc_tk_undefined__parse, // '['
    &lcc_tk_undefined__parse, // '\'
    &lcc_tk_undefined__parse, // ']'
    &lcc_tk_undefined__parse, // '^'
    &lcc_tk_sym__parse, // '_'
    &lcc_tk_undefined__parse, // '`'
    &lcc_tk_sym__parse, // 'a'
    &lcc_tk_sym__parse, // 'b'
    &lcc_tk_sym__parse, // 'c'
    &lcc_tk_sym__parse, // 'd'
    &lcc_tk_sym__parse, // 'e'
    &lcc_tk_sym__parse, // 'f'
    &lcc_tk_sym__parse, // 'g'
    &lcc_tk_sym__parse, // 'h'
    &lcc_tk_sym__parse, // 'i'
    &lcc_tk_sym__parse, // 'j'
    &lcc_tk_sym__parse, // 'k'
    &lcc_tk_sym__parse, // 'l'
    &lcc_tk_sym__parse, // 'm'
    &lcc_tk_sym__parse, // 'n'
    &lcc_tk_sym__parse, // 'o'
    &lcc_tk_sym__parse, // 'p'
    &lcc_tk_sym__parse, // 'q'
    &lcc_tk_sym__parse, // 'r'
    &lcc_tk_sym__parse, // 's'
    &lcc_tk_sym__parse, // 't'
    &lcc_tk_sym__parse, // 'u'
    &lcc_tk_sym__parse, // 'v'
    &lcc_tk_sym__parse, // 'w'
    &lcc_tk_sym__parse, // 'x'
    &lcc_tk_sym__parse, // 'y'
    &lcc_tk_sym__parse, // 'z'
    &lcc_tk_undefined__parse, // '{'
    &lcc_tk_undefined__parse, // '|'
    &lcc_tk_undefined__parse, // '}'
    &lcc_tk_undefined__parse, // '~'
    &lcc_tk_undefined__parse // 'DEL'
};

int lcc_parse_tokens(struct lcc_input_wrapper *input, struct lcc_token *tk) {
    char c = 0;
    if (lcc_input__getc(input, &c) == ERROR)
        return ERROR;
    /* printf("PARSED: '%c'\n", c); */
    lcc_input__ungetc(input, c);
    /* if (c > 127 || c < 0) */
    /*     return lcc_tk_undefined__parse(input, tk); */
    return handlers[c + 1](input, tk);
}
#endif
